// Centralized name mapping: GeoJSON names -> Our Data Keys
export const geoNameMap = {
    "United States of America": "USA",
    "United Kingdom": "UK",
    "United Arab Emirates": "UAE",
    "Czech Republic": "Czechia",
    "Russian Federation": "Russia",
    "Republic of Korea": "South Korea",
    "Dem. Rep. Korea": "North Korea" // If added in future
};

export const mapGeoName = (name) => geoNameMap[name] || name;

// ISO 2-letter codes for FlagCDN
export const countryCodeMapping = {
    "South Korea": "kr",
    "Japan": "jp",
    "Italy": "it",
    "USA": "us",
    "Portugal": "pt",
    "France": "fr",
    "Spain": "es",
    "Germany": "de",
    "UK": "gb",
    "Greece": "gr",
    "Turkey": "tr",
    "Switzerland": "ch",
    "Belgium": "be",
    "Netherlands": "nl",
    "Sweden": "se",
    "Denmark": "dk",
    "Norway": "no",
    "Finland": "fi",
    "Estonia": "ee",
    "Latvia": "lv",
    "Lithuania": "lt",
    "Poland": "pl",
    "Slovakia": "sk",
    "Hungary": "hu",
    "Ireland": "ie",
    "Czechia": "cz",
    "Austria": "at",
    "Canada": "ca",
    "Australia": "au",
    "New Zealand": "nz",
    "Thailand": "th",
    "Vietnam": "vn",
    "China": "cn",
    "Indonesia": "id",
    "Malaysia": "my",
    "Taiwan": "tw",
    "Iceland": "is",
    "Luxembourg": "lu",
    "Slovenia": "si",
    "Croatia": "hr",
    "UAE": "ae",
    "Singapore": "sg",
    "Hong Kong": "hk",
    "Mexico": "mx",
    "Brazil": "br",
    "Argentina": "ar",
    "Peru": "pe",
    "India": "in",
    "Egypt": "eg",
    "Morocco": "ma",
    "Russia": "ru",
    "South Africa": "za",
    "Philippines": "ph",
    "Pakistan": "pk",
    "Saudi Arabia": "sa",
    "Israel": "il",
    "Iran": "ir",
    "Colombia": "co",
    "Chile": "cl",
    "Nigeria": "ng",
    "Ethiopia": "et",
    "Ukraine": "ua",
    "Romania": "ro",
    "Mongolia": "mn",
    "Nepal": "np",
    "Kazakhstan": "kz",
    "Lebanon": "lb",
    "Cuba": "cu",
    "Jamaica": "jm",
    "Kenya": "ke",
    "Uruguay": "uy",
    "Algeria": "dz",
    "Ghana": "gh",
    "Sri Lanka": "lk",
    "Bangladesh": "bd",
    "Bulgaria": "bg",
    "Serbia": "rs",
    "Venezuela": "ve",
    "Ecuador": "ec",
    "Jordan": "jo",
    "Tunisia": "tn",
    "Senegal": "sn",
    "Tanzania": "tz",
};

export const getCountryCode = (name) => countryCodeMapping[name] || null;

// Modern Vibrant Palette
export const countryColorMapping = {
    "Canada": "#f43f5e", "USA": "#3b82f6", "Mexico": "#10b981", "Cuba": "#f59e0b", "Jamaica": "#10b981",
    "Colombia": "#f43f5e", "Venezuela": "#3b82f6", "Ecuador": "#3b82f6", "Peru": "#10b981", "Brazil": "#f59e0b",
    "Chile": "#f43f5e", "Argentina": "#3b82f6", "Uruguay": "#10b981", "UK": "#3b82f6", "Ireland": "#10b981",
    "Portugal": "#10b981", "Spain": "#f59e0b", "France": "#f43f5e", "Belgium": "#10b981", "Netherlands": "#f59e0b",
    "Luxembourg": "#f59e0b", "Germany": "#3b82f6", "Switzerland": "#10b981", "Italy": "#3b82f6", "Austria": "#f59e0b",
    "Czechia": "#f43f5e", "Poland": "#10b981", "Slovakia": "#3b82f6", "Hungary": "#10b981", "Slovenia": "#f43f5e",
    "Croatia": "#3b82f6", "Serbia": "#f43f5e", "Romania": "#f59e0b", "Bulgaria": "#3b82f6", "Ukraine": "#f43f5e",
    "Russia": "#3b82f6", "Norway": "#10b981", "Sweden": "#3b82f6", "Finland": "#f43f5e", "Denmark": "#f43f5e",
    "Estonia": "#10b981", "Latvia": "#f43f5e", "Lithuania": "#f59e0b", "Greece": "#10b981", "Turkey": "#f43f5e",
    "Iceland": "#10b981", "Kazakhstan": "#10b981", "Mongolia": "#f43f5e", "China": "#f59e0b", "India": "#3b82f6",
    "Pakistan": "#f43f5e", "Nepal": "#f43f5e", "Bangladesh": "#f59e0b", "Sri Lanka": "#10b981", "South Korea": "#3b82f6",
    "Japan": "#10b981", "Taiwan": "#10b981", "Hong Kong": "#3b82f6", "Vietnam": "#f43f5e", "Thailand": "#3b82f6",
    "Malaysia": "#10b981", "Singapore": "#f43f5e", "Indonesia": "#3b82f6", "Philippines": "#f59e0b", "UAE": "#3b82f6",
    "Saudi Arabia": "#10b981", "Israel": "#3b82f6", "Jordan": "#f43f5e", "Lebanon": "#10b981", "Iran": "#f59e0b",
    "Egypt": "#f59e0b", "Morocco": "#10b981", "Algeria": "#3b82f6", "Tunisia": "#f43f5e", "Nigeria": "#10b981",
    "Ghana": "#3b82f6", "Senegal": "#10b981", "Kenya": "#10b981", "Ethiopia": "#f43f5e", "Tanzania": "#3b82f6",
    "South Africa": "#f59e0b", "Australia": "#f59e0b", "New Zealand": "#10b981"
};

export const getCountryColor = (name) => countryColorMapping[name] || "#f8fafc";